### ISSUE TITLE
cahracter encoding

### ISSUE THREAD

**Issue by pepo-k** [forensenellanebbia/python27-scripts#1]
not an issue, but more a question or kindly asking for help ...
I have seen in VLC_LastPlayedPosition.py, that you have processed the vlc saved data in vlc-qt-interface.conf
More concretely the [RecentsMRL] section.

I also need to use the info about most recent file played in vlc. I want to use the path and filename in Bash under linux. But somehow I am not able. I am a very beginner, and cannot find out how to used the filename with all the character encoding as eg. 
gate/%21%20pre%20deti/%21%20od%20reny or Angli%C4%8Danina.
For the background, this is coming from slovak characters e.g. č, ť, ž, á, š, ľ
In bash I am not able to process all the %xx characters, it comes error always.
How to encode it correctly?

**Comment by forensenellanebbia** [comment]
I tried to replicate your issue but, as you can see from the screenshot below, the script is working fine. 

![test](https://user-images.githubusercontent.com/8271353/95020487-c4536880-066b-11eb-8211-09cdf9001ee5.png)
